name: Deploy bot to server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 📡 Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd multibot && docker-compose down || true && cd ..
            rm -rf multibot
            git clone https://github.com/magnoliAHAH/multibot.git && cd multibot
            echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env
            docker-compose up -d --build
